
modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/vectorwing/FarmersDelight/issues"
license="MIT License"

[[mods]]
modId = "farmersdelight"
version = "1.19.4-1.2.1"
displayName = "Farmer's Delight"
# updateJSONURL=""
displayURL="https://github.com/vectorwing/FarmersDelight"
logoFile="logo.png"
logoBlur=false
credits="Chloe Dawn, Grimmauld, CDAGaming, TelepathicGrunt, ConductiveFoam, simibubi, Jozufozu, bagel, Silk, SkySom, Eutro, LimonBlaze and many others!"
authors="vectorwing"
description="A lightweight farming and cooking expansion for Minecraft!"
itemIcon="farmersdelight:stove"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.farmersdelight]]
    modId="forge"
mandatory = true
versionRange = "[45.0.29,)"
ordering = "NONE"
    side="BOTH"

[[dependencies.farmersdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
